### ISSUE TITLE
bug: opening from windows search

### ISSUE THREAD

**Issue by hugo9655** [zemoto/WhatAmIHearing#1]
At the moment, each time I open the app, settings don't save. Like for example when I uncheck the box thats enabled by default "keep open in system tray", it doesn't save the fact that I unchecked it on next launch.

**Comment by zemoto** [comment]
The app is made to save those settings, though there is one case I can think of where it would fail.

The settings are saved in the same folder as the app. If you put the app somewhere it does not have write permissions like `Program Files` then it would fail to save. I can get that case fixed real quick.

**Comment by hugo9655** [comment]
Oh hang on I think I know what was happening. I was opening the exe via windows search, but opening it from the folder location works fine. Opening a shortcut to it via windows search also works. Strange.

**Comment by zemoto** [comment]
Ah, that does tell me that there is another issue. It's looking for the settings file via relative path, but that path is incorrect if you open it from Windows Search. So good find regardless.

**Comment by hugo9655** [comment]
Ah ok then. Ig ill reopen for now.

**Comment by zemoto** [comment]
Fixed and released: https://github.com/zemoto/WhatAmIHearing/releases/tag/2.20
