### ISSUE TITLE
"Copy" and "Songwhip" buttons in results window

### ISSUE THREAD

**Issue by ghost** [zemoto/WhatAmIHearing#2]
Hello, this is an awesome app thanks for making it :smile:

It would be great if there were a "Copy" and a "Songwhip" button in the results window that Shazam returns.

The Copy button would copy the track title and artist name returned, and the Songwhip button would search the results on Songwhip just like the Youtube and Spotify buttons do

thank you :smile:

**Comment by zemoto** [comment]
Oh, very nice idea. Going to have to figure out how to fit more buttons. But the more the merrier.

**Comment by zemoto** [comment]
I added a Copy button in the latest 3.0 release https://github.com/zemoto/WhatAmIHearing/releases/tag/3.0

I did not add a `Songwhip` button as it seems it's [on the way to being shut down as of July 22nd](https://songwhip.com/faq/sunset). There is no search anymore so there wouldn't be a good way to make a link atm.

**Comment by ghost** [comment]
Nice, tysm :D

Sucks to see Soundwhip shutting down, I had no idea!! It was so useful
